//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolePro.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSUserRequestRide
    {
        public int SYSUserRequestID { get; set; }
        public int SYSUserID { get; set; }
        public Nullable<bool> RequestStatus { get; set; }
        public string AddPhoneNumber { get; set; }
        public string NumberOfPersons { get; set; }
        public string Charge { get; set; }
        public string Comments { get; set; }
        public int RowCreatedSYSUserID { get; set; }
        public Nullable<System.DateTime> RowCreatedDateTime { get; set; }
        public int RowModifiedSYSUserID { get; set; }
        public Nullable<System.DateTime> RowModifiedDateTime { get; set; }
    
        public virtual SYSUser SYSUser { get; set; }
    }
}
